# Generated by Django 5.1.6 on 2025-02-09 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('order', models.IntegerField()),
                ('base_experience', models.PositiveIntegerField()),
                ('is_shiny', models.BooleanField()),
                ('stats', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pokeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=30)),
                ('border_style', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='home.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='home.poketype'),
        ),
    ]
