# Generated by Django 5.1.6 on 2025-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_pokemon_type_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokecard',
            name='border_style',
            field=models.CharField(choices=[('basic', 'Basic'), ('glitter', 'Glitter'), ('glitch', 'Glitch')], default='basic', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokecard',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('silver', 'Silver'), ('gold', 'Gold'), ('cny', 'Cny'), ('sakura', 'Sakura')], max_length=30),
        ),
    ]
