# Generated by Django 5.1.6 on 2025-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pokecard_border_style_alter_pokecard_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='is_shiny',
        ),
        migrations.AddField(
            model_name='pokecard',
            name='is_shiny',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
